---
title: "Problem Set 37"
author: "Eric Zhou"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Problem 1**
```{r}
ws <- c(62.3, 64.2, 64.4, 65.7, 66.5, 67.6, 68.1, 69.5, 69.8, 70.2, 70.1, 71.9, 74.2, 75.8, 77.1, 76.4, 75.5, 75.0, 74.4, 76.3, 76.5, 76.9, 76.4, 77.9, 79.4, 80.4, 81.0, 80.8, 80.2, 79.9, 80.2, 81.2, 82.2, 80.9, 82.1, 82.5, 81.1, 81.9, 81.8, 81.1)
xs <- seq(1979, 2018, 1)
```

#### **Part a**: 85.38
```{r}
ws.lm <- lm(ws~xs)
newx <- data.frame(xs=c(2019))
predict(ws.lm, newdata=newx, interval="prediction")
```

#### **Part b**: 2050
```{r}
newx <- data.frame(xs=seq(2019, 2050, 1))
predict(ws.lm, newdata=newx, interval="prediction")
```

#### **Part c**: 
```{r}
plot(xs, ws)
abline(ws.lm, col="darkblue")

newx <- data.frame(xs=seq(from=1979, to=2018, by=0.1))
conf_interval <- predict(ws.lm, newdata=newx, interval="confidence", level=0.95)

lines(newx$xs, conf_interval[,2], col="blue", lty=2)
lines(newx$xs, conf_interval[,3], col="blue", lty=2)
```

<br>

## **Problem 2**
#### **Part a**:
```{r}
range(faithful$waiting)
```

#### **Part b**: Look below
#### **Part c**: 
```{r}
faithful.lm <- lm(eruptions~waiting, data=faithful)
newx <- data.frame(waiting=c(50, 70))
predict(faithful.lm, newdata=newx, interval="prediction")
```

#### **Part d**: c because it has smaller range
```{r}
pred <- predict(faithful.lm, newdata=newx, interval="prediction")
pred[,3]-pred[,2]
```


<br>

## **Problem 3**
#### **Part a**: One is 95% range for prediction, one is 95% range for where the average prediction is.
#### **Part b**: Because models are bad.
<br>

## **Problem 4**
```{r}
temp.lm <- lm(Ozone~Temp, data=airquality)
solar.lm <- lm(Ozone~Solar.R, data=airquality)
```

#### **Part a**: 
```{r}
newtempx <- data.frame(Temp=airquality$Temp)
temppred <- predict(temp.lm, newtempx, interval="prediction")
newsolarx <- data.frame(Solar.R=na.omit(airquality$Solar.R))
solarpred <- predict(solar.lm, newsolarx, interval="prediction")
mean(temppred[,3]-temppred[,2])
mean(solarpred[,3]-solarpred[,2])
```

#### **Part b**: Temperature has smaller range which generally makes it better.