---
title: "Problem Set 34"
author: "Eric Zhou"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## **Problem 1**
#### **Part a**: 61.37
#### **Part b**: 13.03
#### **Part c**: 4.71
```{r}
61.37/13.03
```

#### **Part d**: It's pretty much the exact same
#### **Part e**: 61.37, same as mean sq airlines
```{r}
184.1/3
```

#### **Part f**: 13.03, same as mean sq residuals
```{r}
1250.6/96
```

#### **Part g**: 0.004
```{r}
pf(4.711, 3, 96, lower.tail=F)
```


<br>

## **Problem 2**
```{r}
data <- read.csv("C:/Users/ezhou/OneDrive - Eastside Preparatory School/Documents/Eric/2022 - 2023/3 Spring/D Stats/airdelays.csv")
summary(aov(time~airline, data=data))
dim(data)
```

#### **Part a**: 10 possible, 0.005 adjusted
```{r}
choose(5, 2)
0.05/10
```

#### **Part b**: 2.94
```{r}
mean(data$time[data$airline == "U"]) - mean(data$time[data$airline == "H"])
```

#### **Part c**: 0.944
```{r}
sd <- sqrt(11.31)
sqrt(sd^2/length(data$time[data$airline == "U"]) + sd^2/length(data$time[data$airline == "H"]))
```

#### **Part d**: 6.357
#### **Part e**: Significant difference exists
```{r}
pf(6.357, 4, 124, lower.tail=F)
```

